hystrix:
  command:
    clinic-management-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    patient-management-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
